// <auto-generated />
using System;
using HelpDeskTI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDeskTI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407015338_adicionandoMaisCampos")]
    partial class adicionandoMaisCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("HelpDeskTI.Models.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("HelpDeskTI.Models.Chamado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("analistaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("categoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("comentarios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("setor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("solicitanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("analistaId");

                    b.HasIndex("categoriaId");

                    b.HasIndex("solicitanteId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("HelpDeskTI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("perfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HelpDeskTI.Models.Chamado", b =>
                {
                    b.HasOne("HelpDeskTI.Models.Usuario", "analista")
                        .WithMany()
                        .HasForeignKey("analistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskTI.Models.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskTI.Models.Usuario", "solicitante")
                        .WithMany()
                        .HasForeignKey("solicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("analista");

                    b.Navigation("categoria");

                    b.Navigation("solicitante");
                });
#pragma warning restore 612, 618
        }
    }
}
